version: '3'

services:
  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./client/build:/usr/share/nginx/html
  #     - ./client/.nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # server:
  #   build: server/
  #   container_name: server
  #   restart: unless-stopped
  #   ports:
  #     - 5000:5000

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test-pass
    volumes:
      - mongodb_volume:/data/db
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017

  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
    mongodb_volume:
